# Generated by Django 4.2.8 on 2023-12-31 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 20, 37, 39, 927400, tzinfo=datetime.timezone.utc), verbose_name='date uploaded'),
        ),
    ]
